language: R
sudo: false
cache: packages
dist: trusty
env:
  global:
  - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
notifications:
  email: false
r_packages:
  - archivist
  - DALEX2
  - covr

r_github_packages:
  ModelOriented/ceterisParibus2

after_success:
  - Rscript -e 'library(covr); codecov()'
